name: Deploy to Chrome web store

on:
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Zip dist
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip dist

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: "publish" # one of: upload, publish, testers
          client_id: ${{ secrets.CHROME_WEBSTORE_API_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_WEBSTORE_API_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_WEBSTORE_API_REFRESH_TOKEN }}
          extension_id: "nfhfbmbjgdkblicdmdplioanaochdhih"
          zip_file: "release.zip"
